on:
  push:
    branches:
      - master

permissions:
  contents: read

name: release-please

# https://github.com/googleapis/release-please-action
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN_PUBLIC_REPOS }}
          release-type: expo
          target-branch: ${{ github.ref_name }}
